import Link from "next/link";
import { HeroDemo } from "@/components/HeroDemo";
import { LiveStats } from "@/components/LiveStats";
import { Badge, btn } from "@/components/ui";
import { VOICES } from "@/lib/voices";

const FEATURES = [
  { href: "/studio/", title: "Speech studio", body: "Paste a sentence or a whole chapter. Playback starts while the rest is still generating, and you can export WAV.", icon: "M4 12h2m3-5v10m3-13v16m3-11v6m3-9v12m3-7h1" },
  { href: "/projects/", title: "Long-form projects", body: "Multi-voice audiobooks and podcasts. Give each block its own voice and pause, then master everything to one file.", icon: "M5 4h10l4 4v12H5zM14 4v5h5M8 13h8M8 17h5" },
  { href: "/transcribe/", title: "Speech to text", body: "Whisper in the browser: 99 languages, translation to English, SRT and VTT subtitle export.", icon: "M12 4a3 3 0 0 1 3 3v5a3 3 0 0 1-6 0V7a3 3 0 0 1 3-3zM6 11a6 6 0 0 0 12 0M12 17v3" },
  { href: "/voices/", title: `${VOICES.length} voices`, body: "American and British narrators, from warm storytellers to crisp presenters.", icon: "M8 9a3 3 0 1 0 0-.01M3 19c0-3 2.5-5 5-5s5 2 5 5M16 8a2.5 2.5 0 1 0 0-.01M15 14c3 0 6 1.5 6 5" },
  { href: "/developers/", title: "SDK & drop-in API", body: "npm i kelados, or run a drop-in compatible server on your own hardware.", icon: "M8 8l-4 4 4 4M16 8l4 4-4 4M13 6l-2 12" },
  { href: "/dashboard/?tab=lexicon", title: "Pronunciation rules", body: "Teach it brand names and jargon once. Every voice in every app follows the rules.", icon: "M4 6h16M4 12h10M4 18h7M17 15l2 2 3-4" },
];

const COMPARE: [string, string, string][] = [
  ["Price", "Free, forever", "Monthly subscription"],
  ["Character limits", "None", "Monthly credit quota"],
  ["Where audio is generated", "Your device", "Vendor servers"],
  ["Your text is uploaded", "Never", "Every request"],
  ["Source code", "Open (MIT)", "Closed"],
  ["Self-hostable API", "Yes", "No"],
  ["Works offline", "Yes, after first load", "No"],
];

const STEPS = [
  ["01", "Download once", "Your browser fetches an 82M-parameter voice model (~90 MB) from a public CDN, then caches it."],
  ["02", "Generate locally", "WebGPU, or WASM on older devices, runs the model faster than real time on most laptops."],
  ["03", "Keep it private", "Audio is created on your machine and stays there. The server only stores optional projects and settings."],
];

export default function Home() {
  return (
    <>
      <section className="relative overflow-hidden border-b border-line">
        <div className="grid-bg pointer-events-none absolute inset-0" />
        <div className="pointer-events-none absolute left-1/2 top-0 h-[28rem] w-[56rem] -translate-x-1/2 rounded-full bg-accent/10 blur-3xl" />
        <div className="relative mx-auto grid max-w-6xl items-center gap-14 px-5 py-20 md:px-8 md:py-28 lg:grid-cols-[1.1fr_1fr]">
          <div>
            <Badge tone="accent">Open source · MIT licensed</Badge>
            <h1 className="mt-6 text-5xl font-semibold leading-[1.02] tracking-tight md:text-6xl">
              Natural AI voices.<br />
              <span className="font-serif font-normal italic text-muted">Free, unlimited, private.</span>
            </h1>
            <p className="mt-6 max-w-lg text-lg leading-relaxed text-muted">
              Kelados is open-source text-to-speech. Speech is generated by your own browser,
              so there are no credits, no limits and nothing is uploaded. Add it to your apps with one install.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link href="/studio/" className={btn("primary", "lg")}>Open the studio</Link>
              <Link href="/developers/" className={btn("secondary", "lg")}>Developer docs</Link>
            </div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted">
              <span>✓ No sign-up required</span><span>✓ No character limits</span><span>✓ Works offline</span>
            </div>
          </div>
          <HeroDemo />
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-5 py-20 md:px-8">
        <LiveStats />
      </section>

      <section className="mx-auto max-w-6xl px-5 md:px-8">
        <div className="max-w-2xl">
          <p className="text-sm font-medium text-accent">Everything voice</p>
          <h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">One workspace for speech, from a single line to a whole audiobook.</h2>
        </div>
        <div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f) => (
            <Link key={f.title} href={f.href} className="group bg-bg p-7 transition-colors hover:bg-surface">
              <svg viewBox="0 0 24 24" className="size-6 text-accent" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d={f.icon} /></svg>
              <h3 className="mt-5 font-medium">{f.title} <span className="inline-block text-muted transition-transform group-hover:translate-x-0.5">→</span></h3>
              <p className="mt-2 text-sm leading-relaxed text-muted">{f.body}</p>
            </Link>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-5 py-24 md:px-8">
        <div className="max-w-2xl">
          <p className="text-sm font-medium text-accent">How it&apos;s free</p>
          <h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">Paid TTS charges you for their GPUs. Kelados uses yours.</h2>
        </div>
        <div className="mt-12 grid gap-10 md:grid-cols-3">
          {STEPS.map(([n, title, body]) => (
            <div key={n} className="border-t border-line pt-6">
              <span className="font-mono text-sm text-accent">{n}</span>
              <h3 className="mt-3 text-lg font-medium">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted">{body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-5 md:px-8">
        <h2 className="text-3xl font-semibold tracking-tight md:text-4xl">How it compares</h2>
        <p className="mt-2 text-sm text-muted">Compared with typical paid TTS services. Check each vendor for current terms.</p>
        <div className="mt-8 overflow-x-auto rounded-2xl border border-line">
          <table className="w-full min-w-[34rem] text-left text-sm">
            <thead className="bg-surface">
              <tr>
                <th className="p-4 font-normal text-muted" />
                <th className="p-4 font-medium">Kelados</th>
                <th className="p-4 font-normal text-muted">Paid TTS services</th>
              </tr>
            </thead>
            <tbody>
              {COMPARE.map(([k, us, them]) => (
                <tr key={k} className="border-t border-line">
                  <td className="p-4 text-muted">{k}</td>
                  <td className="p-4"><span className="text-ok">✓</span> {us}</td>
                  <td className="p-4 text-muted">{them}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-24 md:px-8 lg:grid-cols-2">
        <div>
          <p className="text-sm font-medium text-accent">For developers</p>
          <h2 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">Three lines of code. No invoice.</h2>
          <p className="mt-4 leading-relaxed text-muted">
            Use the Node SDK or the CLI, or point your existing TTS client at a server you run yourself.
            Optional API keys sync your presets and pronunciation rules.
          </p>
          <Link href="/developers/" className={`${btn("secondary", "md")} mt-8`}>Read the docs →</Link>
        </div>
        <pre className="overflow-x-auto rounded-2xl border border-line bg-surface p-6 font-mono text-[13px] leading-relaxed text-muted">
<span className="text-subtle">{"// npm install kelados"}</span>{"\n"}
<span className="text-accent">import</span> {"{ createKelados }"} <span className="text-accent">from</span> <span className="text-fg">&quot;kelados&quot;</span>;{"\n\n"}
<span className="text-accent">const</span> tts = <span className="text-accent">await</span> createKelados();{"\n"}
<span className="text-accent">const</span> clip = <span className="text-accent">await</span> tts.speak(<span className="text-fg">&quot;Hello, world&quot;</span>, {"{ voice: "}<span className="text-fg">&quot;af_heart&quot;</span>{" }"});{"\n"}
<span className="text-accent">await</span> clip.save(<span className="text-fg">&quot;hello.wav&quot;</span>);
        </pre>
      </section>

      <section className="mx-auto max-w-6xl px-5 md:px-8">
        <div className="relative overflow-hidden rounded-3xl border border-line bg-surface px-6 py-16 text-center">
          <div className="pointer-events-none absolute left-1/2 top-0 h-48 w-[40rem] -translate-x-1/2 rounded-full bg-accent/10 blur-3xl" />
          <h2 className="relative text-3xl font-semibold tracking-tight md:text-5xl">
            Say anything. <span className="font-serif font-normal italic text-muted">It&apos;s on us.</span>
          </h2>
          <p className="relative mx-auto mt-4 max-w-md text-muted">No account needed. Open the studio and start typing.</p>
          <Link href="/studio/" className={`${btn("primary", "lg")} relative mt-8`}>Start for free</Link>
        </div>
      </section>
    </>
  );
}
